export const athletes2024 = [
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete1",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete2",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete3",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete4",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete5",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete6",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete7",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete8",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete9",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete10",
    year: "2024",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
];

export const athletes2023 = [
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete1",
    year: "2023",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete1",
    year: "2023",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete1",
    year: "2023",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
  {
    name: "Erik Olaf Krohnstad",
    img: "/athlete1",
    year: "2023",
    sport: "Football",
    race: "Mechanical Engineering",
    country: "USA",
    university: "University of Chicago",
  },
];
